### ISSUE TITLE
"Dimpling" effect with disk models.

### ISSUE THREAD

**Issue by therob762** [bkloppenborg/simtoi#131]
When using any of the three disk shaders (alpha, andrews, pascucci), the disk "dimples" or displays less flux on the edges of the midplane when viewed at intermediate angles (e.g. 30 or 60 degs).  I can fix this issue by adding 1e6 rings to the disk, but this obviously slows things down accordingly.  I am attaching the .json file so that you can see what I am talking about:

```
{
	"_file_info" : "Save file from the SImulation and Modeling Tool for Optical Interferometry (SIMTOI) version 1.1.0 commit 240693c. See https://github.com/bkloppenborg/simtoi for information about this format",
	"area_height" : 512,
	"area_scale" : 0.050000000000000003,
	"area_width" : 512,
	"model_0" : 
	{
		"base_data" : 
		{
			"T_eff" : [ 5000, 2000, 1000000, false, 100, 0 ],
			"h_cutoff" : [ 1, 0.10000000000000001, 10, false, 1, 2 ],
			"inclination" : [ 60, -180, 180, false, 1, 2 ],
			"n_rings" : [ 1000, 1, 1000, false, 1, 0 ],
			"position_angle" : [ 0, 0, 360, false, 0.10000000000000001, 2 ],
			"r_cutoff" : [ 10, 0.10000000000000001, 20, false, 1, 2 ],
			"r_in" : 
			[
				0.10000000000000001,
				0.10000000000000001,
				10,
				false,
				0.10000000000000001,
				2
			],
			"z_axis_rotation" : [ 0, 0, 360, false, 1, 2 ],
			"z_axis_rotational_period" : [ 0, 0, 100, false, 1, 4 ]
		},
		"base_id" : "disk_andrews2009",
		"position_data" : 
		{
			"E" : [ 0, -1, 1, false, 0.10000000000000001, 2 ],
			"N" : [ 0, -1, 1, false, 0.10000000000000001, 2 ]
		},
		"position_id" : "xy",
		"shader_data" : 
		{
			"R_c" : [ 5, 0.10000000000000001, 6, false, 0.59000000000000008, 1 ],
			"gamma" : [ 1, 0.10000000000000001, 10, false, 0.98999999999999999, 1 ],
			"h_c" : [ 1, 0.10000000000000001, 10, false, 0.98999999999999999, 1 ],
			"kappa" : [ 10, 0.10000000000000001, 10, false, 0.98999999999999999, 1 ],
			"psi" : [ 1, 0.10000000000000001, 10, false, 0.98999999999999999, 1 ],
			"sigma_c" : [ 1, 0.10000000000000001, 100, false, 9.9900000000000002, 1 ]
		},
		"shader_id" : "disk_andrews2009"
	}
}
```

**Comment by bkloppenborg** [comment]
Ah. This is due to the method by which the disks are implemented, namely as a series of concentric rings whose shaders *absorb* light. Notice if we drop the number of rings down to 10, you can clearly see the individual rings:

![screenshot from 2015-07-01 17 03 53](https://cloud.githubusercontent.com/assets/858450/8465940/76920b5e-2013-11e5-9ea0-6efe5560994a.png)

As you increase the number of rings there is more and more absorption (but also more emission above the midplane where there are more rings that intercept the line of sight). If you set the height cutoff for the disk to be zero, then you see only the disk midplane and this pinching effect goes away.

I just added a comment about this on the documentation for the ringed disk models so that others hopefully benefit from our conversation.
