### ISSUE TITLE
Sample files don't have number of digits set up properly.

### ISSUE THREAD

**Issue by therob762** [bkloppenborg/simtoi#137]
By default, SIMTOI only displays one digit which makes it look like the minimization values aren't transferred to the GUI properly (but they are).

**Comment by bkloppenborg** [comment]
The GUI respects the number of decimal places as specified in the save file. Because floating point numbers do not always serialize cleanly when written to a file, the number decimal places are specified in a separate field. See the [wiki entry for the save format](https://github.com/bkloppenborg/simtoi/wiki/JSON-Save-Format) for details. Could you fix the sample files and send in a pull request?

**Comment by bkloppenborg** [comment]
Fixed in ff5286ec2d6a0641daf6c685412542358e9b30be
